### ISSUE TITLE
Move this repo under the jupyterlite org?

### ISSUE THREAD

**Issue by martinRenou** [jupyterlite/xeus-python-demo#1]
Should we move this repo under the JupyterLite org, similar to https://github.com/jupyterlite/demo?

cc. @jtpio @bollwyvl

**Comment by martinRenou** [comment]
Yep! Also it would be nice if a link to the repo could be put in the JupyterLite README, in this section https://jupyterlite.readthedocs.io/en/latest/quickstart/deploy.html

**Comment by jtpio** [comment]
Right the flow is exactly the same but with a different repo.

Probably this alternate repo could be mentioned in the guide, but without making it to complicated or confusing why there are 2 Python kernels. To keep this getting started as simple as possible.

**Comment by jtpio** [comment]
Or we mention it in this section: https://jupyterlite.readthedocs.io/en/latest/quickstart/deploy.html#add-additional-requirements-to-the-deployment

And create a dedicate xeus python guide in https://jupyterlite.readthedocs.io/en/latest/howto/index.html#configuring-the-python-environment

**Comment by martinRenou** [comment]
> Or we mention it in this section: https://jupyterlite.readthedocs.io/en/latest/quickstart/deploy.html#add-additional-requirements-to-the-deployment
And create a dedicate xeus python guide in https://jupyterlite.readthedocs.io/en/latest/howto/index.html#configuring-the-python-environment

Sounds good!

I will initiate the move and update the README

**Comment by jtpio** [comment]
Alright, thanks for working on this!

**Comment by martinRenou** [comment]
Done :) https://github.com/jupyterlite/xeus-python-demo

I can push PRs to update the jupyterlite docs

**Comment by jtpio** [comment]
> I can push PRs to update the jupyterlite docs

That would be great, thanks!
