### ISSUE TITLE
Cells are not executing

### ISSUE THREAD

**Issue by kolibril13** [jupyterlite/xeus-python-demo#21]
I generated https://github.com/Octoframes/jupyter-tldraw-interactive-demo from this template and activated GitHub pages.

This gives me this JupyterLite page:
https://octoframes.github.io/jupyter-tldraw-interactive-demo/lab/index.html

When I now try to execute a cell, it is simply loading forever:
<img width="411" alt="image" src="https://user-images.githubusercontent.com/44469195/235291652-e900551b-c3c3-4f4d-bec8-2d5cb0efe8d5.png">

I tried restarting the kernel, reloading the page and different browsers, but nothing worked.
Any ideas why this is the case?

**Comment by carolusdelyon** [comment]
I have the same problem, with this demo or with a local build. My guess is that there is a dependency problem. Along with the kernel state being stuck in "Unknown", the error that appears in the console is a `BindingError` with the message `Cannot pass non-string to std::string`. I've also tested with configurations prior to the latest commits, such as downgrading the micromamba version to 0.22.0, but nothing.

```
{
    "name": "BindingError",
    "message": "Cannot pass non-string to std::string",
    "stack": "BindingError: Cannot pass non-string to std::string\n    at BindingError.<anonymous> (https://jupyterlite/extensions/@jupyterlite/xeus-python-kernel/static/xpython_wasm.js:9:159188)\n    at new BindingError (eval at createNamedFunction (https://jupyterlite/extensions/@jupyterlite/xeus-python-kernel/static/xpython_wasm.js:9:158847), <anonymous>:4:34)\n    at throwBindingError (https://jupyterlite/extensions/@jupyterlite/xeus-python-kernel/static/xpython_wasm.js:9:159699)\n    at Object.toWireType (https://jupyterlite/extensions/@jupyterlite/xeus-python-kernel/static/xpython_wasm.js:9:194916)\n    at Object.setenv (eval at new_ (https://jupyterlite/extensions/@jupyterlite/xeus-python-kernel/static/xpython_wasm.js:9:183471), <anonymous>:8:26)\n    at Module.init (https://jupyterlite/extensions/@jupyterlite/xeus-python-kernel/static/xpython_wasm.js:9:6006)\n    at async Object.initialize (https://jupyterlite/extensions/@jupyterlite/xeus-python-kernel/static/213.ad40b44dc8626cfbeadb.js?v=ad40b44dc8626cfbeadb:2:12367)"
}
```

**Comment by martinRenou** [comment]
Thanks for opening an issue. @kolibril13 would you be able to show what you have in the JavaScript console?

**Comment by martinRenou** [comment]
Thanks! So it's the same as @carolusdelyon and I can also reproduce this when rebuilding the main demo page.

I'm trying so see if https://github.com/jupyterlite/xeus-python-demo/pull/22 would fix it

**Comment by kolibril13** [comment]
I just updated the project, and cells are executing now!
Thanks for the fix!
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/44469195/235614515-4306b52f-7e44-4e72-b351-69dab5f310d4.png">

**Comment by martinRenou** [comment]
Great! I will be releasing a version of `jupyterlite-xeus-python` that would prevent this situation in the future. You should soon be able to remove the xeus-python constraint from your environment file.
