### ISSUE TITLE
Pin Pydantic to <2.0 in build-environment.yml

### ISSUE THREAD

**Issue by stephenmccalman** [jupyterlite/xeus-python-demo#24]
## Description

[xeus-python-demo](https://github.com/jupyterlite/xeus-python-demo) uses the latest [pydantic](https://github.com/pydantic/pydantic), which is now v2.0.  This appears to create an error in the build of the demo.

```
/home/runner/micromamba-root/envs/build-env/lib/python3.11/site-packages/jupyterlite_core/addons/__init__.py:69: UserWarning: [lite] [jupyterlite-xeus-python] failed to load: To define root models, use `pydantic.RootModel` rather than a field called '__root__'
``` 

While template will build and deploy (despite this error), the environment.yml's package (ipycanvas) is not available in the jupyterlite-xeus-python kernel (after launching the jupyterlite)

Pinning pydantic to <2.0 in the build-environment.yml will allow the demo to build and deploy properly.

## Reproduce

Use to template to create a new demo. 
Add page to github actions

## Context

- Browser and version: Chrome Version 114.0.5735.84

**Comment by stephenmccalman** [comment]
It appears that [empack](https://github.com/emscripten-forge/empack) does not support Pydantic V2 yet. 

https://docs.pydantic.dev/2.0/migration/
namely, 


> We have replaced the use of the __root__ field to specify a "custom root model" with a new type called [RootModel](https://docs.pydantic.dev/2.0/usage/models/#rootmodel-and-custom-root-types) which is intended to replace the functionality of using a field called __root__ in Pydantic V1.

**Comment by martinRenou** [comment]
Thanks for opening an issue! I'm moving it to empack
