### ISSUE TITLE
Failing to import scikit-learn after installing

### ISSUE THREAD

**Issue by cubode** [jupyterlite/xeus-python-demo#27]
## Scikitlearn fails to import

Raises error no module found named unittest.

File /lib/python3.10/site-packages/numpy/testing/__init__.py:8
      1 """Common test support for all numpy test scripts.
      2 
      3 This single module should provide all the common functionality for numpy tests
   (...)
      6 
      7 """
----> 8 from unittest import TestCase
     10 from . import _private
     11 from ._private.utils import *

ModuleNotFoundError: No module named 'unittest'

## Reproduce

name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - scikit-learn

jupyter lite build
jupyter lite serve

- In the notebook in the kernel xeus
import sklearn

## Expected behavior

correctly import scikitlearn

**Comment by DerThorsten** [comment]
> Thanks @cubode for reporting.
> 
> Wondering if this is because of the `empack` filters: https://github.com/emscripten-forge/empack/blob/d6ff060fda66306ffb1367ac0e7f04ccad5f4233/config/empack_config.yaml#L109
> 
> cc @DerThorsten

So adding the testing module might fix this. 
But to me, seems to be that `numpy/testing` is included in the first place.
Is there a stacktrace  / path how  the testing of numpy is imported in the first place?

**Comment by DerThorsten** [comment]
I believe we had the same error recently on emscripten-forge after the bot updated a certain recipe. I think @martinRenou fixed it by using a more recent version of some package (I believe numpy)

**Comment by cubode** [comment]
Thank you for the responses @DerThorsten @jtpio . For me this issue makes xeus unusable, as I really need scikit learn an I can not install in runtime either, all the rest of it is perfect, specially the preinstalling of modules, waiting for your solution thanks :)

**Comment by martinRenou** [comment]
Seems like scikitlearn is importing from numpy/testing all over the place through the utils module: https://github.com/scikit-learn/scikit-learn/blob/80c39a4966ee88150d7e5849ab21a8e17bb1fbc8/sklearn/utils/_testing.py#L34

So either we ask scikitlearn devs to not depend on unittest at runtime, or we don't filter out unittest and patch it if needed...

**Comment by martinRenou** [comment]
I'll push a bug fix soonish
