### ISSUE TITLE
A branch to support Jupyterlite 0.2.x is wanted

### ISSUE THREAD

**Issue by MRYingLEE** [jupyterlite/xeus-python-demo#30]
For unknown reason, I failed to my fork to support Jupyterlite 0.2.x.

So, a branch to support Jupyterlite 0.2.x is wanted as a reference.

Thanks,

**Comment by jtpio** [comment]
Thanks @MRYingLEE.

We need https://github.com/jupyterlite/xeus-python-kernel/pull/155 first, but then yes a branch or draft PR could be useful :+1:

**Comment by MRYingLEE** [comment]
Any progress?
I noticed the jupyterlite xeus related repos had not been updated for more than one month.
Are there some blocks?

**Comment by martinRenou** [comment]
You can contact us on https://quantstack.net/contact.html if you would like more support and more frequent updates :)

**Comment by martinRenou** [comment]
Done
