### ISSUE TITLE
Template `xeus-python-demo` does not build.

### ISSUE THREAD

**Issue by fangohr** [jupyterlite/xeus-python-demo#31]
## Description

Building a clone of the [jupyterlite/xeus-python-demo](https://github.com/jupyterlite/xeus-python-demo) fails.

Symptom: 

https://github.com/fangohr/issue-xeus-python-demo-notbuilding/actions/runs/6887563503/job/18734958333

## Reproduce

1. Go to https://github.com/jupyterlite/xeus-python-demo
2. Click on `Use this template`
3. Decide on a location for the new repository. I have chosen https://github.com/fangohr/issue-xeus-python-demo-notbuilding
4. Github workflows try to execute and fail. 

See output at https://github.com/fangohr/issue-xeus-python-demo-notbuilding/actions/runs/6887563503/job/18734958333#step:5:299

## Expected behavior

Template when forked should build.

**Comment by martinRenou** [comment]
😠 pydantic 2.5 was out and seems to break everything again, I'd suggest downgrading it

**Comment by martinRenou** [comment]
We will hard-pin it down the line and release

**Comment by martinRenou** [comment]
This was fixed. Thanks!
