### ISSUE TITLE
papercut remark

### ISSUE THREAD

**Issue by stonebig** [jupyterlite/xeus-python-demo#5]
Three "about Jupyterlite"in the Help menu of 
https://jupyterlite.github.io/xeus-python-demo/retro/notebooks/?path=demo.ipynb

![image](https://user-images.githubusercontent.com/4312421/209383433-6c93e84d-d034-4c6f-a308-6af1a1dd8138.png)

**Comment by stonebig** [comment]
also I applied the receipe, but the page https://stonebig.github.io/my-demo doesn't want to show up: 404... may there be a missing pre-requisite detail ?

**Comment by stonebig** [comment]
I don't have this in my own working my-demo page... strange.

**Comment by stonebig** [comment]
Awesome ! 

![image](https://user-images.githubusercontent.com/4312421/209438407-a5cea1f6-962a-42bb-b51e-f59e7406957e.png)

**Comment by martinRenou** [comment]
> I don't have this in my own working my-demo page... strange.

Strange indeed! 

Maybe our demo page was built with a broken retrolab version that was fixed later.
